# Generated by Django 2.2 on 2020-11-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nama', max_length=255)),
                ('telp', models.CharField(default='', max_length=15)),
                ('seri', models.CharField(default='ASUS_', max_length=255)),
                ('country', models.CharField(default='jogja', max_length=30)),
                ('kerusakan', models.TextField(default='')),
                ('status', models.CharField(default='pending', max_length=255)),
            ],
        ),
    ]
