# Generated by Django 2.2 on 2020-11-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(default='names', max_length=255)),
                ('series', models.CharField(default='', max_length=15)),
                ('stok', models.CharField(default='10', max_length=30)),
            ],
        ),
    ]
