# Generated by Django 2.2 on 2020-11-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nama', max_length=255)),
                ('telp', models.IntegerField(null=True)),
                ('seri', models.CharField(default='seri', max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
            ],
        ),
    ]
